:doctype: book
:toc: left
:toc-title: Table of Contents
:toclevels: 4
:nofooter:

= Next.js Project

This is a https://nextjs.org/[Next.js] project bootstrapped with https://github.com/vercel/next.js/tree/canary/packages/create-next-app[`create-next-app`].

== Getting Started

First, run the development server:

[source,bash]
----
npm run dev
# or
yarn dev
# or
pnpm dev 
# or
bun dev
----

Open http://localhost:3000[] with your browser to see the result.

You can start editing the page by modifying `app/page.tsx`. The page auto-updates as you edit the file.

This project uses https://nextjs.org/docs/basic-features/font-optimization[`next/font`] to automatically optimize and load Inter, a custom Google Font.

== Learn More

To learn more about Next.js, take a look at the following resources:

* https://nextjs.org/docs[Next.js Documentation] - learn about Next.js features and API.
* https://nextjs.org/learn[Learn Next.js] - an interactive Next.js tutorial.

You can check out https://github.com/vercel/next.js/[the Next.js GitHub repository] - your feedback and contributions are welcome!

== Deploy on Vercel

The easiest way to deploy your Next.js app is to use the https://vercel.com/new?utm_medium=default-template&filter=next.js&utm_source=create-next-app&utm_campaign=create-next-app-readme[Vercel Platform] from the creators of Next.js.

Check out our https://nextjs.org/docs/deployment[Next.js deployment documentation] for more details.

 