host: api.ticketsystem.perry-projects
info:
    contact: { }
    description: This is a Ticketsystem.
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    termsOfService: http://swagger.io/terms/
    title: Ticketsystem API
    version: "1.0"
paths: { }
swagger: "2.0"
