import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/src/styles/globals.scss';
import { PrimeReactProvider } from 'primereact/api';
import { dir } from 'i18next'
import { languages } from '@/src/i18n/settings'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({
    children,
    params: {
        lng,
    }
}: Readonly<{
    children: React.ReactNode,
    params: {
        lng: string,
    },
}>) {
    return (
        <html lang={lng} dir={dir(lng)}>
                <body className={inter.className}>
                    {children}
                </body>
        </html>
    );
}
