import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/src/styles/globals.scss';
import { PrimeReactProvider } from 'primereact/api';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
 
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {    
    return (
        <html>  
            <PrimeReactProvider>
                <body className={inter.className}>
                    {children}
                </body>
            </PrimeReactProvider>
        </html>
    );
}
